<?php

declare(strict_types=1);

namespace ArtisanPackUI\Security\Testing\Reporting\Formats;

use ArtisanPackUI\Security\Testing\Reporting\SecurityFinding;

class MarkdownReportFormat implements ReportFormatInterface
{
    public function format(array $findings, array $metadata, array $summary): string
    {
        $projectName = $metadata['projectName'] ?? 'Security Report';
        $generatedAt = $metadata['generatedAt'] ?? date('c');

        $md = "# Security Report\n\n";
        $md .= "**Project:** {$projectName}\n";
        $md .= "**Generated:** {$generatedAt}\n\n";

        // Summary section
        $md .= "## Summary\n\n";
        $md .= $this->renderSummaryTable($summary);
        $md .= "\n";

        // Quick status
        if (($summary['bySeverity']['critical'] ?? 0) > 0 || ($summary['bySeverity']['high'] ?? 0) > 0) {
            $md .= "> **Status:** Action Required - Critical or high severity findings detected.\n\n";
        } elseif (($summary['bySeverity']['medium'] ?? 0) > 0) {
            $md .= "> **Status:** Review Recommended - Medium severity findings detected.\n\n";
        } else {
            $md .= "> **Status:** No blocking issues found.\n\n";
        }

        // Findings by severity
        $md .= "## Findings\n\n";

        if (empty($findings)) {
            $md .= "No security findings detected.\n\n";
        } else {
            // Group by severity
            $grouped = $this->groupBySeverity($findings);

            foreach (['critical', 'high', 'medium', 'low', 'info'] as $severity) {
                if (! empty($grouped[$severity])) {
                    $md .= $this->renderSeveritySection($severity, $grouped[$severity]);
                }
            }
        }

        // Categories breakdown
        if (! empty($summary['byCategory'])) {
            $md .= "## Findings by Category\n\n";
            $md .= $this->renderCategoryTable($summary['byCategory']);
        }

        // Footer
        $md .= "---\n\n";
        $md .= "*Generated by ArtisanPack Security Testing Framework*\n";

        return $md;
    }

    public function getName(): string
    {
        return 'Markdown';
    }

    public function getExtension(): string
    {
        return 'md';
    }

    public function getMimeType(): string
    {
        return 'text/markdown';
    }

    /**
     * Render the summary table.
     *
     * @param  array<string, mixed>  $summary
     */
    protected function renderSummaryTable(array $summary): string
    {
        $bySeverity = $summary['bySeverity'] ?? [];

        $md = "| Severity | Count |\n";
        $md .= "|----------|-------|\n";

        foreach ($bySeverity as $severity => $count) {
            $icon = $this->getSeverityIcon($severity);
            $md .= "| {$icon} {$severity} | {$count} |\n";
        }

        $total = $summary['total'] ?? array_sum($bySeverity);
        $md .= "| **Total** | **{$total}** |\n";

        return $md;
    }

    /**
     * Group findings by severity.
     *
     * @param  array<SecurityFinding>  $findings
     *
     * @return array<string, array<SecurityFinding>>
     */
    protected function groupBySeverity(array $findings): array
    {
        $groups = [];

        foreach ($findings as $finding) {
            $groups[$finding->severity][] = $finding;
        }

        return $groups;
    }

    /**
     * Render a severity section.
     *
     * @param  array<SecurityFinding>  $findings
     */
    protected function renderSeveritySection(string $severity, array $findings): string
    {
        $icon = $this->getSeverityIcon($severity);
        $md   = "### {$icon} ".ucfirst($severity).' ('.count($findings).")\n\n";

        foreach ($findings as $finding) {
            $md .= $this->renderFinding($finding);
        }

        return $md;
    }

    /**
     * Render a single finding.
     */
    protected function renderFinding(SecurityFinding $finding): string
    {
        $md = "#### {$finding->title}\n\n";
        $md .= "**ID:** `{$finding->id}`\n";
        $md .= "**Category:** {$finding->category}\n";

        if ($finding->location) {
            $md .= "**Location:** `{$finding->location}`\n";
        }

        $md .= "\n{$finding->description}\n\n";

        if ($finding->evidence) {
            $md .= "<details>\n<summary>Evidence</summary>\n\n";
            $md .= "```\n{$finding->evidence}\n```\n\n";
            $md .= "</details>\n\n";
        }

        if ($finding->remediation) {
            $md .= "**Remediation:** {$finding->remediation}\n\n";
        }

        $md .= "---\n\n";

        return $md;
    }

    /**
     * Render the category table.
     *
     * @param  array<string, int>  $categories
     */
    protected function renderCategoryTable(array $categories): string
    {
        $md = "| Category | Findings |\n";
        $md .= "|----------|----------|\n";

        foreach ($categories as $category => $count) {
            $md .= "| {$category} | {$count} |\n";
        }

        return $md."\n";
    }

    /**
     * Get an icon for a severity level.
     */
    protected function getSeverityIcon(string $severity): string
    {
        return match ($severity) {
            'critical' => '🔴',
            'high'     => '🟠',
            'medium'   => '🟡',
            'low'      => '🔵',
            'info'     => '⚪',
            default    => '⚫',
        };
    }
}
