<?php

declare(strict_types=1);

namespace ArtisanPackUI\Security\Services;

use ArtisanPackUI\Security\Contracts\FileValidatorInterface;
use ArtisanPackUI\Security\Contracts\MalwareScannerInterface;
use ArtisanPackUI\Security\Contracts\SecureFileStorageInterface;
use ArtisanPackUI\Security\Events\FileUploaded;
use ArtisanPackUI\Security\Events\FileUploadRejected;
use ArtisanPackUI\Security\Events\MalwareDetected;
use ArtisanPackUI\Security\FileUpload\RequestContext;
use ArtisanPackUI\Security\FileUpload\ScanResult;
use ArtisanPackUI\Security\FileUpload\StoredFile;
use ArtisanPackUI\Security\Models\SecureUploadedFile;
use Illuminate\Filesystem\FilesystemManager;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Str;

class SecureFileStorageService implements SecureFileStorageInterface
{
    /**
     * Create a new secure file storage service instance.
     */
    public function __construct(
        protected FilesystemManager $filesystem,
        protected FileValidatorInterface $validator,
        protected ?MalwareScannerInterface $scanner = null,
    ) {}

    /**
     * Store a validated file securely.
     */
    public function store(UploadedFile $file, array $options = []): StoredFile
    {
        $config = config('artisanpack.security.fileUpload', []);

        // Validate the file first
        $validationResult = $this->validator->validate($file, $options);

        if ($validationResult->failed()) {
            event(new FileUploadRejected(
                $file->getClientOriginalName(),
                $validationResult->getErrors(),
                auth()->user(),
                RequestContext::fromRequest(request())
            ));

            throw new \InvalidArgumentException(
                'File validation failed: '.implode(', ', $validationResult->getErrors())
            );
        }

        // Get storage configuration
        $disk = $options['disk'] ?? $config['storage']['disk'] ?? 'local';
        $basePath = $options['path'] ?? $config['storage']['path'] ?? 'secure-uploads';
        $hashFilenames = $options['hashFilenames'] ?? $config['storage']['hashFilenames'] ?? true;
        $organizeByDate = $options['organizeByDate'] ?? $config['storage']['organizeByDate'] ?? true;

        // Generate storage path
        $storagePath = $this->generateStoragePath($basePath, $organizeByDate);

        // Generate filename
        $filename = $hashFilenames
            ? $this->generateSecureFilename($file)
            : $validationResult->sanitizedFilename ?? $this->validator->sanitizeFilename($file->getClientOriginalName());

        // Full storage path
        $fullPath = rtrim($storagePath, '/').'/'.$filename;

        // Strip EXIF data if configured and file is an image
        if (($config['stripExifData'] ?? true) && str_starts_with($validationResult->detectedMimeType ?? '', 'image/')) {
            $this->validator->stripExifData($file->getPathname());
        }

        // Calculate file hash AFTER EXIF stripping to ensure hash matches stored content
        $hash = hash_file('sha256', $file->getPathname());

        // Store the file
        $this->filesystem->disk($disk)->put($fullPath, file_get_contents($file->getPathname()));

        // Determine initial scan status
        $scanStatus = ScanResult::STATUS_PENDING;
        $threatName = null;

        // Perform malware scan if enabled and not async
        if ($this->scanner && ($config['malwareScanning']['enabled'] ?? false) && ! ($config['malwareScanning']['async'] ?? false)) {
            $scanResult = $this->scanner->scan($file->getPathname());
            $scanStatus = $scanResult->status;
            $threatName = $scanResult->threatName;

            if ($scanResult->isInfected()) {
                // Delete the file and dispatch event
                $this->filesystem->disk($disk)->delete($fullPath);

                event(new MalwareDetected(
                    $file->getClientOriginalName(),
                    $scanResult,
                    auth()->user(),
                    RequestContext::fromRequest(request())
                ));

                throw new \RuntimeException(
                    'Malware detected: '.($scanResult->threatName ?? 'Unknown threat')
                );
            }
        }

        // Create database record (identifier is auto-generated by HasUuids trait)
        $secureFile = SecureUploadedFile::create([
            'original_name' => $file->getClientOriginalName(),
            'storage_path' => $fullPath,
            'disk' => $disk,
            'mime_type' => $validationResult->detectedMimeType ?? $file->getMimeType(),
            'size' => $file->getSize(),
            'hash' => $hash,
            'uploaded_by' => auth()->id(),
            'scan_status' => $scanStatus,
            'threat_name' => $threatName,
            'scanned_at' => $scanStatus !== ScanResult::STATUS_PENDING ? now() : null,
            'metadata' => array_merge($options['metadata'] ?? [], [
                'original_extension' => $file->getClientOriginalExtension(),
                'upload_ip' => request()->ip(),
            ]),
        ]);

        $storedFile = $secureFile->toStoredFile();

        // Dispatch upload event
        event(new FileUploaded($storedFile, auth()->user(), RequestContext::fromRequest(request())));

        return $storedFile;
    }

    /**
     * Retrieve a stored file by its identifier.
     */
    public function retrieve(string $identifier): ?StoredFile
    {
        $file = SecureUploadedFile::where('identifier', $identifier)->first();

        if (! $file) {
            return null;
        }

        return $file->toStoredFile();
    }

    /**
     * Delete a stored file.
     */
    public function delete(string $identifier): bool
    {
        $file = SecureUploadedFile::where('identifier', $identifier)->first();

        if (! $file) {
            return false;
        }

        // Delete from storage
        $file->deleteFromStorage();

        // Delete database record
        $file->delete();

        return true;
    }

    /**
     * Generate a secure URL for file access.
     */
    public function generateSecureUrl(string $identifier, ?int $expirationMinutes = null): string
    {
        $expiration = $expirationMinutes
            ?? config('artisanpack.security.fileUpload.serving.signedUrlExpiration', 60);

        return URL::temporarySignedRoute(
            'secure-file.show',
            now()->addMinutes($expiration),
            ['identifier' => $identifier]
        );
    }

    /**
     * Check if a file exists in storage.
     */
    public function exists(string $identifier): bool
    {
        $file = SecureUploadedFile::where('identifier', $identifier)->first();

        if (! $file) {
            return false;
        }

        return $file->existsInStorage();
    }

    /**
     * Get the file contents.
     */
    public function getContents(string $identifier): ?string
    {
        $file = SecureUploadedFile::where('identifier', $identifier)->first();

        if (! $file) {
            return null;
        }

        return $file->getContents();
    }

    /**
     * Generate the storage path for a file.
     */
    protected function generateStoragePath(string $basePath, bool $organizeByDate): string
    {
        if (! $organizeByDate) {
            return $basePath;
        }

        return sprintf(
            '%s/%s/%s/%s',
            rtrim($basePath, '/'),
            date('Y'),
            date('m'),
            date('d')
        );
    }

    /**
     * Generate a secure filename for storage.
     */
    protected function generateSecureFilename(UploadedFile $file): string
    {
        $extension = strtolower($file->getClientOriginalExtension());
        $hash = Str::random(32);

        return $hash.($extension ? '.'.$extension : '');
    }

    /**
     * Get the model instance for a file.
     */
    public function getModel(string $identifier): ?SecureUploadedFile
    {
        return SecureUploadedFile::where('identifier', $identifier)->first();
    }

    /**
     * Get files pending malware scan.
     */
    public function getPendingScanFiles(int $limit = 100): \Illuminate\Support\Collection
    {
        return SecureUploadedFile::pendingScan()
            ->orderBy('created_at', 'asc')
            ->limit($limit)
            ->get();
    }

    /**
     * Quarantine a file by moving it to the quarantine path.
     */
    public function quarantine(string $identifier): bool
    {
        $file = SecureUploadedFile::where('identifier', $identifier)->first();

        if (! $file) {
            return false;
        }

        $quarantinePath = config('artisanpack.security.fileUpload.malwareScanning.quarantinePath');

        if (! $quarantinePath) {
            return false;
        }

        // Store original path before any modifications
        $originalPath = $file->storage_path;
        $newPath = $quarantinePath.'/'.$file->identifier.'_'.basename($originalPath);

        // Get file contents before moving
        $contents = $file->getContents();
        if ($contents === null) {
            return false;
        }

        // Write to quarantine using Storage facade (local disk)
        $writeSuccess = $this->filesystem->disk('local')->put($newPath, $contents);
        if (! $writeSuccess) {
            return false;
        }

        // Only delete from original storage after successful write
        $file->deleteFromStorage();

        // Update record with original_path captured before modifications
        $file->update([
            'storage_path' => $newPath,
            'disk' => 'local', // Quarantine is always local
            'metadata' => array_merge($file->metadata ?? [], [
                'quarantined_at' => now()->toIso8601String(),
                'original_path' => $originalPath,
            ]),
        ]);

        return true;
    }
}
